version: '3.4'

services:
  mongodb_container:
    image: mongodb/mongodb-community-server:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  file-converter-client:
    image: ${DOCKER_REGISTRY-}fileconverterclient
    build:
      context: .
      dockerfile: file-converter-client/Dockerfile
  file-converter-api:
    image: ${DOCKER_REGISTRY-}fileconverterapi
    build:
      context: .
      dockerfile: file-converter-api/Dockerfile
volumes:
  mongodb_data_container:
#mongodb://root:rootpassword@localhost:27017