version: '3.4'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
  fileconverterclient:
    image: ${DOCKER_REGISTRY-}fileconverterclient
    build:
      context: .
      dockerfile: file-converter-client/Dockerfile
  fileconverterapi:
    image: ${DOCKER_REGISTRY-}fileconverterapi
    build:
      context: .
      dockerfile: file-converter-api/Dockerfile
    depends_on:
         - mongodb

#mongodb://root:rootpassword@localhost:27017